apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: todo-research
spec:
  selector:
    app: auth-service
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP