apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-research

resources:
  - namespace.yaml
  - pvc.yaml
  - init-configmap.yaml
  - postgres-auth.yaml
  - postgres-todo.yaml
  - redis.yaml
  - auth-deployment.yaml
  - auth-service.yaml
  - todo-deployment.yaml
  - todo-service.yaml
  - notification-deployment.yaml
  - notification-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - hpa.yaml

  # ini opsional