apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: todo-research
spec:
  selector:
    app: notification-service
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  type: ClusterIP