apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-research
spec:
  selector:
    app: todo-service
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  type: ClusterIP