apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: todo-app
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
